package lv.luhmirins.folk.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF276c17)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFa9f68f)
val md_theme_light_onPrimaryContainer = Color(0xFF002200)
val md_theme_light_secondary = Color(0xFF2f6b26)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFb0f49d)
val md_theme_light_onSecondaryContainer = Color(0xFF002200)
val md_theme_light_tertiary = Color(0xFF006784)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbae9ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001f2a)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFdfe5d7)
val md_theme_light_onSurfaceVariant = Color(0xFF43493f)
val md_theme_light_outline = Color(0xFF73796e)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2d3132)

val md_theme_dark_primary = Color(0xFF8ed976)
val md_theme_dark_onPrimary = Color(0xFF013a00)
val md_theme_dark_primaryContainer = Color(0xFF085300)
val md_theme_dark_onPrimaryContainer = Color(0xFFa9f68f)
val md_theme_dark_secondary = Color(0xFF95d784)
val md_theme_dark_onSecondary = Color(0xFF003a00)
val md_theme_dark_secondaryContainer = Color(0xFF155210)
val md_theme_dark_onSecondaryContainer = Color(0xFFb0f49d)
val md_theme_dark_tertiary = Color(0xFF61d3ff)
val md_theme_dark_onTertiary = Color(0xFF003546)
val md_theme_dark_tertiaryContainer = Color(0xFF004d64)
val md_theme_dark_onTertiaryContainer = Color(0xFFbae9ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF43493f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc3c8bc)
val md_theme_dark_outline = Color(0xFF8d9387)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)

val seed = Color(0xFF4a9037)
val error = Color(0xFFba1b1b)